/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjetsRouteImport } from './routes/projets'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as LivrablesRouteImport } from './routes/livrables'
import { Route as CompetencesRouteImport } from './routes/competences'
import { Route as IndexRouteImport } from './routes/index'

const ProjetsRoute = ProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrablesRoute = LivrablesRouteImport.update({
  id: '/livrables',
  path: '/livrables',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetencesRoute = CompetencesRouteImport.update({
  id: '/competences',
  path: '/competences',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/competences': typeof CompetencesRoute
  '/livrables': typeof LivrablesRoute
  '/presentation': typeof PresentationRoute
  '/projets': typeof ProjetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/competences': typeof CompetencesRoute
  '/livrables': typeof LivrablesRoute
  '/presentation': typeof PresentationRoute
  '/projets': typeof ProjetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/competences': typeof CompetencesRoute
  '/livrables': typeof LivrablesRoute
  '/presentation': typeof PresentationRoute
  '/projets': typeof ProjetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/competences' | '/livrables' | '/presentation' | '/projets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/competences' | '/livrables' | '/presentation' | '/projets'
  id:
    | '__root__'
    | '/'
    | '/competences'
    | '/livrables'
    | '/presentation'
    | '/projets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompetencesRoute: typeof CompetencesRoute
  LivrablesRoute: typeof LivrablesRoute
  PresentationRoute: typeof PresentationRoute
  ProjetsRoute: typeof ProjetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projets': {
      id: '/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof ProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livrables': {
      id: '/livrables'
      path: '/livrables'
      fullPath: '/livrables'
      preLoaderRoute: typeof LivrablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competences': {
      id: '/competences'
      path: '/competences'
      fullPath: '/competences'
      preLoaderRoute: typeof CompetencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompetencesRoute: CompetencesRoute,
  LivrablesRoute: LivrablesRoute,
  PresentationRoute: PresentationRoute,
  ProjetsRoute: ProjetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
